# Generated by Django 6.0.3 on 2026-03-23 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_student_qr_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'course')},
        ),
    ]
